################################################################################
# Automatically-generated file. Do not edit!
################################################################################

-include ../../makefile.local

# Add inputs and outputs from these tool invocations to the build variables 
OBJ_SRCS_QUOTED += \
"../build-project_mpc5604b-FLASH/Sources/CW_Startup_vle.obj" \
"../build-project_mpc5604b-FLASH/Sources/Dem.obj" \
"../build-project_mpc5604b-FLASH/Sources/Det.obj" \
"../build-project_mpc5604b-FLASH/Sources/Dio.obj" \
"../build-project_mpc5604b-FLASH/Sources/Dio_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Dio_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Dio_Siul_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/EcuM.obj" \
"../build-project_mpc5604b-FLASH/Sources/Exceptions.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_NonASR.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Pit_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Pit_LLD_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Rtc_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Rtc_LLD_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Stm_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_Stm_LLD_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_eMIOS_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Gpt_eMIOS_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/IOClient_Com.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_NonASR.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_Reg_eSys_eMIOS.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_Siul_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_Siul_LLD_IRQ.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_WKPU_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_WKPU_LLD_IRQ.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_eMIOS_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Icu_eMIOS_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/IntcInterrupts.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Dma_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Dmamux_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Ecsm_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Flash_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Clocks_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Modes_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Monitor_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Power_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Reset_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Mcu_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Port.obj" \
"../build-project_mpc5604b-FLASH/Sources/Port_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Port_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Port_Siul_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_NonASR.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_Reg_eSys_eMIOS.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_eMIOS_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Pwm_eMIOS_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Reg_eSys_eMIOS_Gpt.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Adc.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Can.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Dio.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Eth.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Fls.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Gpt.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Icu.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Mcu.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Port.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Pwm.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_RamTst.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Spi.obj" \
"../build-project_mpc5604b-FLASH/Sources/SchM_Wdg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Vector_vle_mcal.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_Cfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_Irq.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_Lcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_PBcfg.obj" \
"../build-project_mpc5604b-FLASH/Sources/Wdg_Swt_LLD.obj" \
"../build-project_mpc5604b-FLASH/Sources/_Data_Definitions.obj" \
"../build-project_mpc5604b-FLASH/Sources/_ISRs.obj" \
"../build-project_mpc5604b-FLASH/Sources/_Init.obj" \
"../build-project_mpc5604b-FLASH/Sources/_Motion_Control.obj" \
"../build-project_mpc5604b-FLASH/Sources/_Ringbuff.obj" \
"../build-project_mpc5604b-FLASH/Sources/_Sensors_Control.obj" \
"../build-project_mpc5604b-FLASH/Sources/_colision_control.obj" \
"../build-project_mpc5604b-FLASH/Sources/_main.obj" \
"../build-project_mpc5604b-FLASH/Sources/_serial.obj" \
"../build-project_mpc5604b-FLASH/Sources/_testing.obj" \
"../build-project_mpc5604b-FLASH/Sources/stdio_ext.obj" \

OBJ_SRCS += \
../build-project_mpc5604b-FLASH/Sources/CW_Startup_vle.obj \
../build-project_mpc5604b-FLASH/Sources/Dem.obj \
../build-project_mpc5604b-FLASH/Sources/Det.obj \
../build-project_mpc5604b-FLASH/Sources/Dio.obj \
../build-project_mpc5604b-FLASH/Sources/Dio_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Dio_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Dio_Siul_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/EcuM.obj \
../build-project_mpc5604b-FLASH/Sources/Exceptions.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_NonASR.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Pit_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Pit_LLD_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Rtc_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Rtc_LLD_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Stm_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_Stm_LLD_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_eMIOS_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Gpt_eMIOS_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/IOClient_Com.obj \
../build-project_mpc5604b-FLASH/Sources/Icu.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_NonASR.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_Reg_eSys_eMIOS.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_Siul_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_Siul_LLD_IRQ.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_WKPU_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_WKPU_LLD_IRQ.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_eMIOS_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Icu_eMIOS_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/IntcInterrupts.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Dma_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Dmamux_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Ecsm_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Flash_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Clocks_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Modes_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Monitor_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Power_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_MC_Reset_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Mcu_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Port.obj \
../build-project_mpc5604b-FLASH/Sources/Port_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Port_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Port_Siul_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_NonASR.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_Reg_eSys_eMIOS.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_eMIOS_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Pwm_eMIOS_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Reg_eSys_eMIOS_Gpt.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Adc.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Can.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Dio.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Eth.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Fls.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Gpt.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Icu.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Mcu.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Port.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Pwm.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_RamTst.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Spi.obj \
../build-project_mpc5604b-FLASH/Sources/SchM_Wdg.obj \
../build-project_mpc5604b-FLASH/Sources/Vector_vle_mcal.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_Cfg.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_Irq.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_Lcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_PBcfg.obj \
../build-project_mpc5604b-FLASH/Sources/Wdg_Swt_LLD.obj \
../build-project_mpc5604b-FLASH/Sources/_Data_Definitions.obj \
../build-project_mpc5604b-FLASH/Sources/_ISRs.obj \
../build-project_mpc5604b-FLASH/Sources/_Init.obj \
../build-project_mpc5604b-FLASH/Sources/_Motion_Control.obj \
../build-project_mpc5604b-FLASH/Sources/_Ringbuff.obj \
../build-project_mpc5604b-FLASH/Sources/_Sensors_Control.obj \
../build-project_mpc5604b-FLASH/Sources/_colision_control.obj \
../build-project_mpc5604b-FLASH/Sources/_main.obj \
../build-project_mpc5604b-FLASH/Sources/_serial.obj \
../build-project_mpc5604b-FLASH/Sources/_testing.obj \
../build-project_mpc5604b-FLASH/Sources/stdio_ext.obj \


# Each subdirectory must supply rules for building sources it contributes

